import {
    doc,
    serverTimestamp,
    setDoc,
} from "firebase/firestore";
import { db } from "@/lib/firebase";

const EXPERT_SPECIALTY_GROUPS = [
    {
        id: "crop_production",
        title: "Crop production",
        order: 10,
        items: [
            "Crop disease diagnosis",
            "Crop nutrition management",
            "Crop production planning",
            "Seed selection and variety advice",
            "Maize production",
            "Wheat production",
            "Rice production",
            "Potato production",
            "Legume production",
            "Root crop production",
        ],
    },
    {
        id: "horticulture",
        title: "Horticulture",
        order: 20,
        items: [
            "Greenhouse production",
            "Tomato production",
            "Onion production",
            "Fruit production",
            "Vegetable production",
            "Flower production",
            "Nursery management",
            "Protected crop production",
            "Post-harvest handling",
            "Export horticulture compliance",
        ],
    },
    {
        id: "soil_land_management",
        title: "Soil and land management",
        order: 30,
        items: [
            "Soil testing interpretation",
            "Soil fertility management",
            "Soil conservation",
            "Land preparation planning",
            "Erosion control",
            "Compost and manure management",
            "Farm soil rehabilitation",
            "Soil amendment recommendations",
        ],
    },
    {
        id: "crop_protection",
        title: "Crop protection",
        order: 40,
        items: [
            "Pest identification and management",
            "Plant disease identification",
            "Integrated pest management",
            "Weed management",
            "Pesticide selection guidance",
            "Biological pest control",
            "Crop scouting",
            "Plant health assessment",
        ],
    },
    {
        id: "livestock_health",
        title: "Livestock health",
        order: 50,
        items: [
            "General veterinary consultation",
            "Livestock disease diagnosis",
            "Vaccination planning",
            "Parasite control",
            "Animal treatment follow-up",
            "Herd health management",
            "Biosecurity planning",
            "Breeding health assessment",
        ],
    },
    {
        id: "livestock_production",
        title: "Livestock production",
        order: 60,
        items: [
            "Dairy production",
            "Beef production",
            "Goat production",
            "Sheep production",
            "Pig production",
            "Rabbit production",
            "Pasture management",
            "Livestock housing",
            "Herd management",
        ],
    },
    {
        id: "poultry",
        title: "Poultry",
        order: 70,
        items: [
            "Broiler production",
            "Layer production",
            "Indigenous poultry production",
            "Poultry disease management",
            "Poultry nutrition",
            "Poultry housing",
            "Hatchery management",
            "Poultry biosecurity",
        ],
    },
    {
        id: "animal_nutrition",
        title: "Animal nutrition",
        order: 80,
        items: [
            "Feed formulation",
            "Dairy cow nutrition",
            "Beef cattle nutrition",
            "Poultry feed formulation",
            "Pig nutrition",
            "Mineral supplementation",
            "Fodder planning",
            "Feed quality assessment",
        ],
    },
    {
        id: "irrigation_water",
        title: "Irrigation and water",
        order: 90,
        items: [
            "Irrigation system design",
            "Drip irrigation",
            "Sprinkler irrigation",
            "Water requirement planning",
            "Irrigation scheduling",
            "Water harvesting",
            "Farm water storage",
            "Irrigation troubleshooting",
        ],
    },
    {
        id: "agricultural_engineering",
        title: "Agricultural engineering",
        order: 100,
        items: [
            "Farm machinery selection",
            "Farm machinery maintenance",
            "Post-harvest equipment",
            "Farm structure design",
            "Greenhouse structure planning",
            "Renewable energy for farms",
            "Farm automation",
            "Agricultural equipment assessment",
        ],
    },
    {
        id: "agribusiness_finance",
        title: "Agribusiness and finance",
        order: 110,
        items: [
            "Farm business planning",
            "Agricultural investment planning",
            "Farm budgeting",
            "Cost of production analysis",
            "Market linkage",
            "Value chain development",
            "Agricultural finance advice",
            "Farm record keeping",
            "Profitability analysis",
            "Business model development",
        ],
    },
    {
        id: "farm_management",
        title: "Farm management",
        order: 120,
        items: [
            "Farm operations planning",
            "Farm staff management",
            "Farm productivity assessment",
            "Farm record systems",
            "Production scheduling",
            "Input procurement planning",
            "Farm risk management",
            "Farm performance review",
        ],
    },
    {
        id: "sustainable_farming",
        title: "Organic and sustainable farming",
        order: 130,
        items: [
            "Organic farming transition",
            "Organic certification preparation",
            "Regenerative agriculture",
            "Climate-smart agriculture",
            "Agroecology",
            "Conservation agriculture",
            "Integrated farming systems",
            "Sustainable input management",
        ],
    },
    {
        id: "aquaculture",
        title: "Aquaculture",
        order: 140,
        items: [
            "Fish farming setup",
            "Pond management",
            "Fish nutrition",
            "Aquaculture disease management",
            "Water quality management",
            "Fish breeding",
            "Aquaculture business planning",
        ],
    },
    {
        id: "beekeeping",
        title: "Beekeeping",
        order: 150,
        items: [
            "Apiary setup",
            "Bee colony management",
            "Honey production",
            "Bee disease and pest management",
            "Hive inspection",
            "Honey processing",
            "Beekeeping business planning",
        ],
    },
    {
        id: "food_safety_processing",
        title: "Food safety and processing",
        order: 160,
        items: [
            "Food safety compliance",
            "Farm produce quality assurance",
            "HACCP preparation",
            "Dairy processing",
            "Meat handling and hygiene",
            "Crop processing",
            "Packaging and labelling",
            "Post-harvest loss reduction",
        ],
    },
    {
        id: "agricultural_technology",
        title: "Agricultural technology",
        order: 170,
        items: [
            "Precision agriculture",
            "Farm data management",
            "Digital farm records",
            "Remote crop monitoring",
            "Farm sensor systems",
            "Drone applications in agriculture",
            "Agricultural software consulting",
            "Smart irrigation systems",
        ],
    },
];

export async function seedExpertSpecialties() {
    for (const group of EXPERT_SPECIALTY_GROUPS) {
        await setDoc(
            doc(
                db,
                "expert_specialty_groups",
                group.id
            ),
            {
                title: group.title,
                items: group.items,
                order: group.order,
                active: true,
                createdAt:
                    serverTimestamp(),
                updatedAt:
                    serverTimestamp(),
            },
            {
                merge: true,
            }
        );
    }
}